services:
  postgres:
    image: postgres:17-alpine
    container_name: cotizaciones_postgres
    environment:
      POSTGRES_DB: cotizaciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cotizaciones_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5434:80"
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local