services:
  postgres:
    image: postgres:17-alpine
    container_name: cotizaciones_postgres
    environment:
      POSTGRES_DB: cotizaciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local